# Generated by Django 4.2.4 on 2023-08-11 23:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_description_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog')),
                ('description', ckeditor.fields.RichTextField()),
                ('is_home', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
    ]
