# Generated by Django 4.2.4 on 2023-08-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog_cprogramming_blog_java_blog_javascript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='popular',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
