# Generated by Django 4.2.4 on 2023-08-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_popular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='CProgramming',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='java',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='javascript',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='popular',
        ),
        migrations.AddField(
            model_name='blog',
            name='topics',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
