# Generated by Django 4.2.4 on 2023-08-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blog_cprogramming_remove_blog_java_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='python',
        ),
    ]
