# Generated by Django 4.2.4 on 2023-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog_category_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.ManyToManyField(to='blog.blog'),
        ),
    ]
