# Generated by Django 4.2.4 on 2023-08-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_category_blog_blog_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='topweek',
            name='last_week',
            field=models.BooleanField(default=False),
        ),
    ]
